[project]
name = 'tablecrow'
description = 'abstract interface with remote database table'
readme = 'README.md'
requires-python = '>=3.8'
license = { file = 'LICENSE' }
authors = [{ name = 'Zach Burnett', email = 'zachary.r.burnett@gmail.com' }]
dependencies = [
    'psycopg2-binary',
    'pyproj',
    'python-dateutil',
    'shapely',
    'spatialite',
    'sshtunnel',
    'typepigeon >=1.0.2',
]
dynamic = ['version']

[project.optional-dependencies]
test = [
    'pytest',
    'wget',
]
docs = [
    'm2r2',
    'sphinx',
    'sphinx-rtd-theme',
]

[project.urls]
'documentation' = 'https://tablecrow.readthedocs.io'
'repository' = 'https://github.com/zacharyburnett/TableCrow'

[build-system]
requires = [
    'setuptools >=42',
    'setuptools_scm[toml] >=3.4',
    'wheel',
    'oldest-supported-numpy',
]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]

[tool.setuptools.packages.find]